export const RoscaSecureABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "DEFAULT_BAN_THRESHOLD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_MEMBERS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_PERIOD_SECONDS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelCircle",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "circleDetails",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "name", type: "bytes", internalType: "bytes" },
      { name: "desc", type: "bytes", internalType: "bytes" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "circles",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "contract IERC20" },
      { name: "contributionAmount", type: "uint256", internalType: "uint256" },
      { name: "periodDuration", type: "uint256", internalType: "uint256" },
      { name: "maxMembers", type: "uint256", internalType: "uint256" },
      { name: "collateralFactor", type: "uint256", internalType: "uint256" },
      { name: "insuranceFee", type: "uint256", internalType: "uint256" },
      { name: "startTimestamp", type: "uint256", internalType: "uint256" },
      { name: "currentRound", type: "uint256", internalType: "uint256" },
      { name: "roundStart", type: "uint256", internalType: "uint256" },
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoscaSecure.CircleState",
      },
      { name: "rotationLocked", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimPayout",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contribute",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createCircle",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_desc", type: "string", internalType: "string" },
      { name: "token", type: "address", internalType: "address" },
      { name: "contributionAmount", type: "uint256", internalType: "uint256" },
      { name: "periodDuration", type: "uint256", internalType: "uint256" },
      { name: "maxMembers", type: "uint256", internalType: "uint256" },
      { name: "collateralFactor", type: "uint256", internalType: "uint256" },
      { name: "insuranceFee", type: "uint256", internalType: "uint256" },
      {
        name: "initialPayoutOrder",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "emergencyWithdraw",
    inputs: [
      { name: "circleId", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeRoundIfExpired",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCircleDetails",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "desc", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCircleInfo",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tokenAddr", type: "address", internalType: "address" },
      { name: "contributionAmount", type: "uint256", internalType: "uint256" },
      { name: "periodDuration", type: "uint256", internalType: "uint256" },
      { name: "maxMembers", type: "uint256", internalType: "uint256" },
      { name: "collateralFactor", type: "uint256", internalType: "uint256" },
      { name: "insuranceFee", type: "uint256", internalType: "uint256" },
      { name: "startTimestamp", type: "uint256", internalType: "uint256" },
      { name: "currentRound", type: "uint256", internalType: "uint256" },
      { name: "roundStart", type: "uint256", internalType: "uint256" },
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoscaSecure.CircleState",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInsurancePool",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberInfo",
    inputs: [
      { name: "circleId", type: "uint256", internalType: "uint256" },
      { name: "member", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "collateralLocked", type: "uint256", internalType: "uint256" },
      {
        name: "insuranceContributed",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "defaults", type: "uint256", internalType: "uint256" },
      { name: "banned", type: "bool", internalType: "bool" },
      { name: "withdrawnCollateral", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMembers",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPayoutOrder",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundDeposited",
    inputs: [
      { name: "circleId", type: "uint256", internalType: "uint256" },
      { name: "roundId", type: "uint256", internalType: "uint256" },
      { name: "member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "insurancePool",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinCircle",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "members",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "collateralLocked", type: "uint256", internalType: "uint256" },
      {
        name: "insuranceContributed",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "defaults", type: "uint256", internalType: "uint256" },
      { name: "banned", type: "bool", internalType: "bool" },
      { name: "withdrawnCollateral", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextCircleId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingPayouts",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawCollateral",
    inputs: [{ name: "circleId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CircleCompleted",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CircleCreated",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CollateralWithdrawn",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ContributionMade",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DefaultDetected",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "slashed",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EmergencyWithdraw",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemberBanned",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemberJoined",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "collateralLocked",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "insuranceFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PayoutClaimed",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "claimer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundStarted",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "startedAt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WinnerSelected",
    inputs: [
      {
        name: "circleId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "winner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "pot", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
